development:
  adapter: postgresql
  encoding: utf8
  database: db/blog_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: blog_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: blog_production
  pool: 5
  timeout: 5000
